
language: c
sudo: false
dist: trusty

env:
    - LUA="lua=5.1"
    - LUA="lua=5.2"
    - LUA="lua=5.3"
    - LUA="luajit=2.0"
    - LUA="luajit=2.1"

install:
    - luarocks install moonscript
    # - luarocks install lua-toml # Broken rockspec being hosted on Luarocks.
    - git clone https://github.com/jonstoler/lua-toml && cp lua-toml/toml.lua .
    - luarocks install argparse
    - luarocks install luafilesystem
    - luarocks install busted
    - luarocks install luacov-coveralls

before_install:
    - pip3 install hererocks
    - hererocks lua_install -r^ --$LUA
    - export PATH=$PATH:$PWD/lua_install/bin

script:
    - busted --verbose

after_success:
    - luacov-coveralls -i "%.moon" -e "spec"

cache:
    directories:
        - lua_install

addons:
    apt:
        packages:
            - python3-pip

